<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>net.tascalate.javaflow</groupId>
		<artifactId>net.tascalate.javaflow.parent</artifactId>
		<version>2.9.0</version>
		<relativePath>../</relativePath>
	</parent>

	<artifactId>net.tascalate.javaflow.api</artifactId>
	<packaging>jar</packaging>

	<name>Tascalate JavaFlow / API + Internal Core</name>

	<properties>
		<license.header>../HEADER-DERRIVED.txt</license.header>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.moditect</groupId>
				<artifactId>moditect-maven-plugin</artifactId>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<executions>
					<execution>
						<id>compile-java21</id>
						<goals>
							<goal>compile</goal>
						</goals>
						<configuration>
							<jdkToolchain>
								<version>21</version>
							</jdkToolchain>
							<release>21</release>
							<compilerArgs>
								<arg>--enable-preview</arg>
							</compilerArgs>
							<compileSourceRoots>
								<compileSourceRoot>${project.basedir}/src/main/java21</compileSourceRoot>
							</compileSourceRoots>
							<outputDirectory>${project.build.outputDirectory}/META-INF/versions/21</outputDirectory>
						</configuration>
					</execution> 
					<execution>
						<id>compile-java22</id>
						<goals>
							<goal>compile</goal>
						</goals>
						<configuration>
							<jdkToolchain>
								<version>22</version>
							</jdkToolchain>
							<release>22</release>
							<compilerArgs>
								<arg>--enable-preview</arg>
							</compilerArgs>
							<compileSourceRoots>
								<compileSourceRoot>${project.basedir}/src/main/java21</compileSourceRoot>
							</compileSourceRoots>
							<outputDirectory>${project.build.outputDirectory}/META-INF/versions/22</outputDirectory>
						</configuration>
					</execution> 
					<execution>
						<id>compile-java23</id>
						<goals>
							<goal>compile</goal>
						</goals>
						<configuration>
							<jdkToolchain>
								<version>23</version>
							</jdkToolchain>
							<release>23</release>
							<compilerArgs>
								<arg>--enable-preview</arg>
							</compilerArgs>
							<compileSourceRoots>
								<compileSourceRoot>${project.basedir}/src/main/java21</compileSourceRoot>
							</compileSourceRoots>
							<outputDirectory>${project.build.outputDirectory}/META-INF/versions/23</outputDirectory>
						</configuration>
					</execution> 
					<execution>
						<id>compile-java24</id>
						<goals>
							<goal>compile</goal>
						</goals>
						<configuration>
							<jdkToolchain>
								<version>24</version>
							</jdkToolchain>
							<release>24</release>
							<compilerArgs>
								<arg>--enable-preview</arg>
							</compilerArgs>
							<compileSourceRoots>
								<compileSourceRoot>${project.basedir}/src/main/java24</compileSourceRoot>
							</compileSourceRoots>
							<outputDirectory>${project.build.outputDirectory}/META-INF/versions/24</outputDirectory>
						</configuration>
					</execution> 
					<execution>
						<id>compile-java25</id>
						<goals>
							<goal>compile</goal>
						</goals>
						<configuration>
							<jdkToolchain>
								<version>25</version>
							</jdkToolchain>
							<release>25</release>
							<compileSourceRoots>
								<compileSourceRoot>${project.basedir}/src/main/java25</compileSourceRoot>
							</compileSourceRoots>
							<outputDirectory>${project.build.outputDirectory}/META-INF/versions/25</outputDirectory>
						</configuration>
					</execution> 
				</executions>
				<configuration>
					<source>1.6</source>
					<target>1.6</target>
					<!--
					<debug>false</debug>
					-->
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>
