<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<parent>
		<groupId>net.tascalate.javaflow</groupId>
		<artifactId>net.tascalate.javaflow.parent</artifactId>
		<version>2.9.0</version>
		<relativePath>../</relativePath>
	</parent>

	<artifactId>net.tascalate.javaflow.api-jvmc</artifactId>
	<packaging>jar</packaging>

	<name>Tascalate JavaFlow / API via Java 21+ Continuations</name>

	<properties>
		<license.header>../HEADER-DERRIVED.txt</license.header>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
		</dependency>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<executions>
					<execution>
						<id>default-compile</id>
						<goals>
							<goal>compile</goal>
						</goals>
						<configuration>
							<jdkToolchain>
								<version>21</version>
								<vendor>Oracle</vendor>
							</jdkToolchain>
							<excludes combine.self="override" />
						</configuration>
					</execution> 
				</executions>
				<configuration>
					<source>21</source>
					<target>21</target>
					<compilerArgs>
						<arg>--enable-preview</arg>
						<arg>--add-exports</arg>
						<arg>java.base/jdk.internal.vm=net.tascalate.javaflow.api</arg>
					</compilerArgs>
					<!--
					<debug>false</debug>
					-->
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<executions>
					<execution>
						<id>unpack-binaries-java25</id>
						<phase>prepare-package</phase>
						<goals>
							<goal>unpack</goal>
						</goals>
						<configuration>
							<artifactItems>
								<artifactItem>
									<groupId>${project.groupId}</groupId>
									<artifactId>${project.groupId}.api-j25</artifactId>
									<version>${project.version}</version>
									<type>jar</type>
									<overWrite>true</overWrite>
									<outputDirectory>${project.build.outputDirectory}/META-INF/versions/25</outputDirectory>
									<includes>**/PlatformContinuationExecutor.class,**/ScopedValueContinuationExecutor.class,**/module-info.class</includes>
								</artifactItem>
							</artifactItems>
							<failOnMissingClassifierArtifact>true</failOnMissingClassifierArtifact>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
		<pluginManagement>
			<plugins>
				<plugin>
					<groupId>org.apache.maven.plugins</groupId>
					<artifactId>maven-javadoc-plugin</artifactId>
					<executions>
						<execution>
							<id>attach-javadocs</id>
							<goals>
								<goal>jar</goal>
							</goals>
							<configuration>
								<jdkToolchain>
									<version>21</version>
									<vendor>Oracle</vendor>
								</jdkToolchain>
								<source>21</source>
								<target>21</target>
								<legacyMode>true</legacyMode>
								<additionalOptions>
									<additionalOption>--enable-preview</additionalOption>
								</additionalOptions>
								<!-- 2. Forces underlying javadoc.exe process to bypass module layout -->
								<additionalJOptions>
									<additionalJOption>--add-exports=java.base/jdk.internal.vm=ALL-UNNAMED</additionalJOption>
									<additionalJOption>--add-opens=java.base/jdk.internal.vm=ALL-UNNAMED</additionalJOption>
								</additionalJOptions>
							</configuration>	
						</execution>
					</executions>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>

</project>
